const data = [
    {
        "price": 3.89,
        "name": "Red Bench",
        "image": "https://images.pexels.com/photos/1172253/pexels-photo-1172253.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "id": 2,
        "featured": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T09:58:37.648925+00:00",
        "category": "people",
        "bestseller": true
      },
      {
        "price": 100,
        "name": "Man",
        "image": "https://images.pexels.com/photos/235922/pexels-photo-235922.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 3,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:00:50.010033+00:00",
        "category": "people",
        "bestseller": true
      },
      {
        "price": 93.89,
        "name": "Egg Ballon",
        "image": "https://images.pexels.com/photos/1034940/pexels-photo-1034940.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 5,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:02:28.79902+00:00",
        "category": "food",
        "bestseller": false
      },
      {
        "price": 101,
        "name": "Archictecture",
        "image": "https://images.pexels.com/photos/4226100/pexels-photo-4226100.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 6,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:04:40.439107+00:00",
        "category": "landmarks",
        "bestseller": false
      },
      {
        "price": 101,
        "name": "Samurai King Restling",
        "image": "https://images.pexels.com/photos/1553958/pexels-photo-1553958.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 7,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:07:35.709386+00:00",
        "category": "landmarks",
        "bestseller": false
      },
      {
        "price": 15,
        "name": "Summers Day",
        "image": "https://images.pexels.com/photos/1154638/pexels-photo-1154638.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 8,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:10:40.390009+00:00",
        "category": "people",
        "bestseller": false
      },
      {
        "price": 123,
        "name": "King Protea",
        "image": "https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 9,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:11:53.180938+00:00",
        "category": "landmarks",
        "bestseller": false
      },
      {
        "price": 12.4,
        "name": "Cake roll",
        "image": "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 10,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:14:25.235246+00:00",
        "category": "food",
        "bestseller": false
      },
      {
        "price": 23.8,
        "name": "Cookies Delight",
        "image": "https://images.pexels.com/photos/239581/pexels-photo-239581.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 11,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:15:21.364057+00:00",
        "category": "food",
        "bestseller": true
      },
      {
        "price": 19.4,
        "name": "Bread Roll",
        "image": "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 12,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:16:11.764025+00:00",
        "category": "food",
        "bestseller": false
      },
      {
        "price": 400,
        "name": "Rotweiler",
        "image": "https://images.pexels.com/photos/850602/pexels-photo-850602.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 13,
        "featured": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:25:27.821151+00:00",
        "category": "pets",
        "bestseller": true
      },
      {
        "price": 23.8,
        "name": "Cats love",
        "image": "https://images.pexels.com/photos/1643456/pexels-photo-1643456.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 14,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:26:59.001788+00:00",
        "category": "pets",
        "bestseller": false
      },
      {
        "price": 34.2,
        "name": "Animal love",
        "image": "https://www.pexels.com/photo/black-cat-on-sofa-1931370/",
        "id": 15,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:27:58.62908+00:00",
        "category": "pets",
        "bestseller": false
      },
      {
        "price": 32.3,
        "name": "Guard Owners",
        "image": "https://images.pexels.com/photos/3448793/pexels-photo-3448793.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 16,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:28:35.796222+00:00",
        "category": "pets",
        "bestseller": false
      },
      {
        "price": 90,
        "name": "Tokyo View",
        "image": "https://images.pexels.com/photos/3448793/pexels-photo-3448793.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 17,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:29:22.692289+00:00",
        "category": "cities",
        "bestseller": false
      },
      {
        "price": 12.3,
        "name": "Flying Area",
        "image": "https://images.pexels.com/photos/3834331/pexels-photo-3834331.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 18,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:29:52.039641+00:00",
        "category": "cities",
        "bestseller": false
      },
      {
        "price": 23.8,
        "name": "Rainbow love",
        "image": "https://images.pexels.com/photos/3834331/pexels-photo-3834331.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 19,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:31:02.917599+00:00",
        "category": "nature",
        "bestseller": false
      },
      {
        "price": 67.9,
        "name": "Lonely Forest",
        "image": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 20,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:31:28.168832+00:00",
        "category": "nature",
        "bestseller": false
      },
      {
        "price": 43,
        "name": "Beautiful Night",
        "image": "https://images.pexels.com/photos/3293148/pexels-photo-3293148.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 21,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:32:40.487327+00:00",
        "category": "nature",
        "bestseller": false
      },
      {
        "price": 32,
        "name": "In Love",
        "image": "https://images.pexels.com/photos/6532978/pexels-photo-6532978.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        "id": 22,
        "featured": false,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "currency": "USD",
        "created_at": "2021-04-22T10:33:39.760586+00:00",
        "category": "people",
        "bestseller": false
      }
]

export default data;